export const SKILLS = [
    'Next.js',
    'React',
    'Jest',
    'Redux',
    'React Query',
    'Node.js',
    'Express',
    'TailwindCSS',
    'Bootstrap',
    'ChakraUI',
    'MongoDB',
    'Prisma',
    'SASS',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'Git',
    'React Router',
    'React Hook Form',
    'Github',
    'Framer',
];